version: 2

sources:
  - name: spotify
    database: peerless-text-491310-n5
    schema: spotify

    tables:
      - name: tracks
        identifier: tracks
        description: Raw Spotify tracks data

        columns:
          - name: date_date
            description: Date of the track record

          - name: id
            description: Unique track ID
            tests: 
              - unique
              - not_null

          - name: name
            description: Track name

          - name: popularity
            description: Popularity score

          - name: duration_ms
            description: Duration in milliseconds

          - name: explicit
            description: Explicit content flag

          - name: artists
            description: Artist names

          - name: id_artists
            description: Artist IDs

          - name: release_date
            description: Release date of the track

          - name: danceability
            description: Danceability score

          - name: energy
            description: Energy level

          - name: key
            description: Musical key

          - name: loudness
            description: Loudness in dB

          - name: mode
            description: Mode (major/minor)

          - name: speechiness
            description: Speechiness measure

          - name: acousticness
            description: Acousticness score

          - name: instrumentalness
            description: Instrumentalness score

          - name: liveness
            description: Liveness score

          - name: valence
            description: Valence (positivity)

          - name: tempo
            description: Tempo (BPM)

          - name: time_signature
            description: Time signature

      - name: artist
        identifier: artists
        description: Spotify artist data
        columns:
            
          - name: id
            description: Unique track ID
            tests:
              - unique
              - not_null

          - name: followers
            description: Count of followers
          
          - name: genres
            description: Genres of artist
          
          - name: name
            description: Artist name

          - name: popularity
            description: Artist's popularity

      - name: artist_genres
        identifier: artists

        columns:
          - name: artist_id
            description: id

          - name: genres
            description: Genres of artist

          - name: followers
            description: Count of followers
          
          - name: popularity
            description: Popularity of artist
      
      - name: genres_tracks
        identifier: genres_tracks
        columns:
          - name: track_genre
            description: track_genre
            
          - name: id
            description: id


models:
  - name: stg_tracks
    description: "Spotify track verisinin staging modeli"
  - name: stg_artist
    description: "Spotify artist verisinin staging modeli"
  - name: stg_genres
    description: "Muzik turleri"
